USE GrupoC;

INSERT IGNORE INTO Espectaculo(Nombre_espectaculo, Descripcion, Tipo) VALUES

('Concierto Dua Lipa', 'Gira internacional pop', 'musical'),
('Concierto Ed Sheeran', 'Tour acústico internacional', 'musical'),
('Concierto Imagine Dragons', 'Rock alternativo internacional', 'musical'),
('Concierto Vetusta Morla', 'Gira española indie', 'musical'),
('Concierto Love of Lesbian', 'Festival indie nacional', 'musical'),
('Concierto David Bisbal', 'Tour español', 'musical'),
('Concierto Alejandro Sanz', 'Concierto acústico', 'musical'),
('Concierto Karol G', 'Gira urbana internacional', 'musical'),
('Concierto Mora', 'Concierto urbano latino', 'musical'),
('Concierto Feid', 'Tour latinoamericano', 'musical'),

('Festival Sonorama Ribera', 'Festival indie español', 'cultural'),
('Festival O Son do Camiño', 'Festival gallego', 'cultural'),
('Festival BBK Live', 'Festival internacional de música', 'cultural'),
('Festival Starlite Marbella', 'Festival veraniego', 'cultural'),
('Festival de Jazz de San Sebastián', 'Festival musical de jazz', 'cultural'),
('Exposición Dalí Inmersiva', 'Experiencia artística', 'cultural'),
('Exposición Picasso', 'Colección de arte moderno', 'cultural'),
('Semana del Cine Fantástico', 'Festival cinematográfico', 'cultural'),
('Feria Internacional del Libro', 'Evento cultural literario', 'cultural'),
('Gala de Ballet Nacional', 'Representación de danza clásica', 'cultural'),

('Partido España-Francia', 'Partido amistoso internacional', 'deportivo'),
('Partido Lakers-Celtics', 'Partido NBA internacional', 'deportivo'),
('Final Champions League', 'Final europea de fútbol', 'deportivo'),
('Maratón de Madrid', 'Evento deportivo popular', 'deportivo'),
('Copa Davis', 'Competición internacional de tenis', 'deportivo'),
('Final Mundial Baloncesto', 'Final internacional FIBA', 'deportivo'),
('GP de Cataluña MotoGP', 'Competición de motociclismo', 'deportivo'),
('Torneo ATP Barcelona', 'Competición ATP', 'deportivo'),
('Partido Intercontinental', 'Competición internacional', 'deportivo'),
('Supercopa de España', 'Competición nacional', 'deportivo'),

('Mamma Mia!', 'Musical internacional', 'teatral'),
('El Fantasma de la Ópera', 'Musical clásico', 'teatral'),
('Romeo y Julieta', 'Drama clásico', 'teatral'),
('La Vida es Sueño', 'Teatro clásico español', 'teatral'),
('El Método Grönholm', 'Comedia teatral', 'teatral'),
('Perfectos Desconocidos', 'Adaptación teatral', 'teatral'),
('La Función que Sale Mal', 'Comedia internacional', 'teatral'),
('Toc Toc', 'Comedia psicológica', 'teatral'),
('Don Quijote de la Mancha', 'Representación clásica', 'teatral'),
('La Llamada', 'Musical contemporáneo', 'teatral'),

('Comic Con España', 'Convención internacional', 'otro'),
('Congreso IA y Big Data', 'Evento tecnológico', 'otro'),
('Salón del Manga', 'Convención cultural japonesa', 'otro'),
('Gala de Premios del Cine', 'Premios cinematográficos', 'otro'),
('Evento TEDx Madrid', 'Charlas y conferencias', 'otro'),
('Expo Gaming España', 'Evento de videojuegos', 'otro'),
('Convención Blockchain', 'Tecnología financiera', 'otro'),
('Feria Internacional de Turismo', 'Evento empresarial', 'otro'),
('Cumbre de Innovación Europea', 'Evento profesional', 'otro'),
('Hackathon Nacional', 'Competición tecnológica', 'otro'),


-- Top peliculas
-- Top 100 Películas más taquilleras (Actualizado 2026)
('Avatar', 'Épica de ciencia ficción en Pandora', 'cine'),
('Avengers: Endgame', 'Culminación de la saga original de Marvel', 'cine'),
('Avatar: El sentido del agua', 'Continuación de la odisea en los océanos', 'cine'),
('Titanic', 'Drama romántico y catástrofe histórica', 'cine'),
('Ne Zha 2', 'Fenómeno de la animación mitológica china', 'cine'),
('Star Wars: El despertar de la Fuerza', 'El regreso de la saga galáctica', 'cine'),
('Avengers: Infinity War', 'El inicio del conflicto final con Thanos', 'cine'),
('Spider-Man: No Way Home', 'Crossover multiversal del hombre araña', 'cine'),
('Zootopia 2', 'Nueva aventura policial en la metrópolis animal', 'cine'),
('Inside Out 2', 'Nuevas emociones en la mente de Riley', 'cine'),
('Jurassic World', 'Reapertura del parque de dinosaurios', 'cine'),
('El Rey León (2019)', 'Remake fotorrealista del clásico Disney', 'cine'),
('The Avengers', 'La primera reunión de los héroes de Marvel', 'cine'),
('Furious 7', 'Acción extrema y despedida de Paul Walker', 'cine'),
('Top Gun: Maverick', 'Regreso triunfal a los cielos de Tom Cruise', 'cine'),
('Avatar: Fuego y Ceniza', 'Tercera entrega de la saga de James Cameron', 'cine'),
('Frozen II', 'Aventura musical en el bosque encantado', 'cine'),
('Barbie', 'Comedia existencial en el mundo de Barbieland', 'cine'),
('Avengers: Age of Ultron', 'Lucha contra la inteligencia artificial', 'cine'),
('Super Mario Bros: La película', 'Aventura animada del fontanero de Nintendo', 'cine'),
('Black Panther', 'Introducción al reino tecnológico de Wakanda', 'cine'),
('Harry Potter y las Reliquias de la Muerte 2', 'El enfrentamiento final contra Voldemort', 'cine'),
('Deadpool & Wolverine', 'Crossover gamberro del universo mutante', 'cine'),
('Star Wars: Los últimos Jedi', 'Continuación del viaje de Rey y Luke', 'cine'),
('Jurassic World: El reino caído', 'Rescate de dinosaurios de una isla volcánica', 'cine'),
('Frozen', 'Historia de dos hermanas y el poder del hielo', 'cine'),
('La Bella y la Bestia (2017)', 'Adaptación en imagen real del cuento musical', 'cine'),
('Los Increíbles 2', 'El regreso de la familia de superhéroes', 'cine'),
('Fast & Furious 8', 'Traición y persecuciones de alta velocidad', 'cine'),
('Iron Man 3', 'Tony Stark se enfrenta a sus miedos', 'cine'),
('Minions', 'Origen de los ayudantes amarillos de Gru', 'cine'),
('Capitán América: Civil War', 'Conflicto interno entre los Vengadores', 'cine'),
('Aquaman', 'Aventura épica en el reino de Atlantis', 'cine'),
('El Señor de los Anillos: El retorno del Rey', 'Conclusión de la misión para destruir el anillo', 'cine'),
('Spider-Man: Far From Home', 'Peter Parker se enfrenta a Mysterio en Europa', 'cine'),
('Capitana Marvel', 'Historia de origen de la heroína espacial', 'cine'),
('Transformers: El lado oscuro de la Luna', 'Guerra robótica en la Tierra y la Luna', 'cine'),
('Skyfall', 'Misión personal y crítica de James Bond', 'cine'),
('Transformers: La era de la extinción', 'Nueva generación de humanos y robots', 'cine'),
('The Dark Knight Rises', 'Conclusión de la trilogía de Batman de Nolan', 'cine'),
('Joker', 'Origen psicológico del villano de Gotham', 'cine'),
('Star Wars: El ascenso de Skywalker', 'Final de la saga principal de los Skywalker', 'cine'),
('Toy Story 4', 'Woody encuentra un nuevo propósito de vida', 'cine'),
('Toy Story 3', 'Los juguetes se enfrentan a la guardería Sunnyside', 'cine'),
('Piratas del Caribe: El cofre del hombre muerto', 'Jack Sparrow huye de Davy Jones', 'cine'),
('Vaiana 2', 'Nueva travesía por los mares de Oceanía', 'cine'),
('Rogue One: Una historia de Star Wars', 'Misión rebelde para robar los planos del Imperio', 'cine'),
('Aladdin (2019)', 'El genio de la lámpara en acción real', 'cine'),
('Star Wars: La amenaza fantasma', 'Inicio cronológico de la saga Skywalker', 'cine'),
('Piratas del Caribe: En mareas misteriosas', 'Búsqueda de la fuente de la juventud', 'cine'),
('Gru: Mi villano favorito 3', 'Gru conoce a su hermano gemelo Dru', 'cine'),
('Jurassic Park', 'La obra maestra original de Spielberg', 'cine'),
('Buscando a Dory', 'Dory busca sus orígenes en el océano', 'cine'),
('Alicia en el país de las maravillas (2010)', 'Visión fantástica de Tim Burton', 'cine'),
('Zootrópolis', 'Misterio en la ciudad de los mamíferos', 'cine'),
('El Hobbit: Un viaje inesperado', 'Inicio de la aventura de Bilbo Bolsón', 'cine'),
('El Caballero Oscuro', 'Batman contra el Joker de Heath Ledger', 'cine'),
('Harry Potter y la piedra filosofal', 'El niño que sobrevivió llega a Hogwarts', 'cine'),
('Jumanji: Bienvenidos a la jungla', 'Aventura dentro de un videojuego retro', 'cine'),
('Harry Potter y las Reliquias de la Muerte 1', 'Comienzo de la búsqueda de los Horrocruxes', 'cine'),
('Gru 4: Mi villano favorito', 'Nuevas travesuras de la familia de Gru', 'cine'),
('El Rey León (1994)', 'El clásico animado más exitoso de Disney', 'cine'),
('Harry Potter y el misterio del príncipe', 'Sexto año de Harry en Hogwarts', 'cine'),
('El Hobbit: La desolación de Smaug', 'Encuentro con el dragón bajo la montaña', 'cine'),
('El Hobbit: La batalla de los cinco ejércitos', 'Final de la trilogía de la Tierra Media', 'cine'),
('Harry Potter y la Orden del Fénix', 'Resistencia contra la burocracia ministerial', 'cine'),
('Buscando a Nemo', 'Un pez payaso cruza el océano por su hijo', 'cine'),
('Harry Potter y el cáliz de fuego', 'El torneo de los tres magos y el regreso del mal', 'cine'),
('Spider-Man 3', 'El hombre araña contra el simbionte negro', 'cine'),
('La asistenta (2026)', 'Thriller de misterio doméstico basado en el bestseller', 'cine'),
('La saga Crepúsculo: Amanecer - Parte 2', 'Final de la historia de Bella y Edward', 'cine'),
('Harry Potter y la cámara secreta', 'Misterios antiguos se revelan en el colegio', 'cine'),
('Ice Age 3: El origen de los dinosaurios', 'La manada bajo el hielo prehistórico', 'cine'),
('Spectre', 'James Bond contra una organización secreta', 'cine'),
('Spider-Man: Homecoming', 'Primer vuelo solitario de Peter en el MCU', 'cine'),
('Bohemian Rhapsody', 'Biopic musical de Freddie Mercury y Queen', 'cine'),
('Shrek 2', 'La secuela más exitosa del ogro verde', 'cine'),
('Jumanji: Siguiente nivel', 'Regreso al juego con nuevos avatares', 'cine'),
('El libro de la selva (2016)', 'Aventura salvaje de Mowgli en imagen real', 'cine'),
('Harry Potter y el prisionero de Azkaban', 'Encuentro con Sirius Black y los dementores', 'cine'),
('El Señor de los Anillos: Las dos torres', 'La defensa de la Tierra Media continúa', 'cine'),
('Star Wars: La venganza de los Sith', 'La transformación de Anakin en Darth Vader', 'cine'),
('Inside Out (2015)', 'Las emociones controlan la mente de Riley', 'cine'),
('Mascotas', 'La vida secreta de los animales cuando no estás', 'cine'),
('Wonder Woman', 'Origen de la guerrera amazona en la guerra', 'cine'),
('Pegasus 3', 'Carreras de coches épicas en el cine chino', 'cine'),
('Transformers: La venganza de los caídos', 'Segunda guerra entre Autobots y Decepticons', 'cine'),
('Origen (Inception)', 'Atracos dentro de los sueños humanos', 'cine'),
('Super Mario Galaxy', 'Expansión espacial del universo de Mario', 'cine'),
('Spider-Man (2002)', 'La película que inició el fenómeno moderno', 'cine'),
('El Señor de los Anillos: La comunidad del anillo', 'Inicio del viaje hacia Mordor', 'cine'),
('Wolf Warrior 2', 'Acción bélica y patriótica china', 'cine'),
('E.T. el extraterrestre', 'La amistad entre un niño y un alienígena', 'cine'),
('Guardianes de la Galaxia Vol. 2', 'Aventura cósmica y búsqueda familiar', 'cine'),
('El código Da Vinci', 'Misterio histórico en las calles de París', 'cine'),
('Independence Day', 'Resistencia mundial contra una invasión alien', 'cine'),
('Star Wars: El retorno del Jedi', 'El enfrentamiento final de la trilogía original', 'cine'),
('Shrek Tercero', 'El ogro busca un heredero para el trono', 'cine'),
('Harry Potter y las Reliquias de la Muerte 2 (Reestreno)', 'Especial aniversario en cines IMAX', 'cine'),
('Gladiator', 'Épica de justicia y honor en la antigua Roma', 'cine');