USE GrupoC;

INSERT IGNORE INTO Espectaculo(Nombre_espectaculo, Descripcion, Tipo) VALUES

('Concierto Dua Lipa', 'Gira internacional pop', 'musical'),
('Concierto Ed Sheeran', 'Tour acústico internacional', 'musical'),
('Concierto Imagine Dragons', 'Rock alternativo internacional', 'musical'),
('Concierto Vetusta Morla', 'Gira española indie', 'musical'),
('Concierto Love of Lesbian', 'Festival indie nacional', 'musical'),
('Concierto David Bisbal', 'Tour español', 'musical'),
('Concierto Alejandro Sanz', 'Concierto acústico', 'musical'),
('Concierto Karol G', 'Gira urbana internacional', 'musical'),
('Concierto Mora', 'Concierto urbano latino', 'musical'),
('Concierto Feid', 'Tour latinoamericano', 'musical'),

('Festival Sonorama Ribera', 'Festival indie español', 'cultural'),
('Festival O Son do Camiño', 'Festival gallego', 'cultural'),
('Festival BBK Live', 'Festival internacional de música', 'cultural'),
('Festival Starlite Marbella', 'Festival veraniego', 'cultural'),
('Festival de Jazz de San Sebastián', 'Festival musical de jazz', 'cultural'),
('Exposición Dalí Inmersiva', 'Experiencia artística', 'cultural'),
('Exposición Picasso', 'Colección de arte moderno', 'cultural'),
('Semana del Cine Fantástico', 'Festival cinematográfico', 'cultural'),
('Feria Internacional del Libro', 'Evento cultural literario', 'cultural'),
('Gala de Ballet Nacional', 'Representación de danza clásica', 'cultural'),

('Partido España-Francia', 'Partido amistoso internacional', 'deportivo'),
('Partido Lakers-Celtics', 'Partido NBA internacional', 'deportivo'),
('Final Champions League', 'Final europea de fútbol', 'deportivo'),
('Maratón de Madrid', 'Evento deportivo popular', 'deportivo'),
('Copa Davis', 'Competición internacional de tenis', 'deportivo'),
('Final Mundial Baloncesto', 'Final internacional FIBA', 'deportivo'),
('GP de Cataluña MotoGP', 'Competición de motociclismo', 'deportivo'),
('Torneo ATP Barcelona', 'Competición ATP', 'deportivo'),
('Partido Intercontinental', 'Competición internacional', 'deportivo'),
('Supercopa de España', 'Competición nacional', 'deportivo'),

('Mamma Mia!', 'Musical internacional', 'teatral'),
('El Fantasma de la Ópera', 'Musical clásico', 'teatral'),
('Romeo y Julieta', 'Drama clásico', 'teatral'),
('La Vida es Sueño', 'Teatro clásico español', 'teatral'),
('El Método Grönholm', 'Comedia teatral', 'teatral'),
('Perfectos Desconocidos', 'Adaptación teatral', 'teatral'),
('La Función que Sale Mal', 'Comedia internacional', 'teatral'),
('Toc Toc', 'Comedia psicológica', 'teatral'),
('Don Quijote de la Mancha', 'Representación clásica', 'teatral'),
('La Llamada', 'Musical contemporáneo', 'teatral'),

('Comic Con España', 'Convención internacional', 'otro'),
('Congreso IA y Big Data', 'Evento tecnológico', 'otro'),
('Salón del Manga', 'Convención cultural japonesa', 'otro'),
('Gala de Premios del Cine', 'Premios cinematográficos', 'otro'),
('Evento TEDx Madrid', 'Charlas y conferencias', 'otro'),
('Expo Gaming España', 'Evento de videojuegos', 'otro'),
('Convención Blockchain', 'Tecnología financiera', 'otro'),
('Feria Internacional de Turismo', 'Evento empresarial', 'otro'),
('Cumbre de Innovación Europea', 'Evento profesional', 'otro'),
('Hackathon Nacional', 'Competición tecnológica', 'otro');